version: "3"
services:
  minirootfs:
    image: ghcr.io/kou029w/yama/minirootfs
    volumes:
      - ./cache:/etc/apk/cache
      - ./apkovl/etc/apk/repositories:/etc/apk/repositories
      - ./apkovl/etc/apk/world:/etc/apk/world
