name: build
on:
  workflow_dispatch:
  push: { branches: [master] }
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y qemu-user-static
      - run: docker login docker.pkg.github.com -u "${GITHUB_ACTOR}" -p "${{ github.token }}"
      - run: bin/build
      - run: docker-compose push
