name: build
on:
  push: { branches: [main] }
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install -y qemu-user-static
      - run: bin/build
      - run: sudo bin/img-gen
