name: build
on:
  schedule: [{ cron: "0 21 * * sun" }] # Every Monday at 6am Asia/Tokyo UTC+9
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login docker.pkg.github.com -u "${GITHUB_ACTOR}" -p "${{ github.token }}"
      - run: bin/build
      - run: docker-compose push
